version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  target-branch: master
  ignored_updates:
    - match:
        dependency_name: "google.golang.org/grpc"
